openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact Book API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    This is an API documentation for the Contact Book backend application.

tags:
  - name: Auth
    description: User authentication and registration
  - name: Contacts
    description: Managing contacts

servers:
  - url: https://nodejs-hw-mongodb-7-qxr1.onrender.com
  - url: http://localhost:3000

security:
  - bearerAuth: []

paths:
  /contacts:
    get:
      tags:
        - Contacts
      summary: Get all contacts
      parameters:
        - $ref: '../swagger/components/parameters/pagination.yaml#/page'
        - $ref: '../swagger/components/parameters/pagination.yaml#/perPage'
        - $ref: '../swagger/components/parameters/pagination.yaml#/sortOrder'
        - $ref: '../swagger/components/parameters/pagination.yaml#/isFavourite'
        - $ref: '../swagger/components/parameters/pagination.yaml#/contactType'
        - $ref: '../swagger/components/parameters/pagination.yaml#/sortBy'
      responses:
        '200':
          description: Contacts successfully found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Contacts successfully found
                  data:
                    type: object
                    properties:
                      contacts:
                        type: array
                        items:
                          $ref: '#/components/schemas/Contact'
                      page:
                        type: integer
                        example: 1
                      perPage:
                        type: integer
                        example: 10
                      totalItems:
                        type: integer
                        example: 25
                      totalPages:
                        type: integer
                        example: 3
                      hasPreviousPage:
                        type: boolean
                        example: false
                      hasNextPage:
                        type: boolean
                        example: true
    post:
      $ref: '../swagger/paths/contacts/post.yaml'

  /contacts/{contactId}:
    get:
      tags:
        - Contacts
      summary: Get contact by ID
      parameters:
        - $ref: ../swagger/components/parameters/contactId.yaml
      responses:
        '200':
          description: Contact successfully found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Contact successfully found
                  data:
                    $ref: '#/components/schemas/Contact'
    patch:
      $ref: '../swagger/paths/contacts/{contactId}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{contactId}/delete.yaml'

  /auth/register:
    $ref: ../swagger/paths/contacts/auth/register.yaml
  /auth/login:
    $ref: ../swagger/paths/contacts/auth/login.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Contact:
      type: object
      properties:
        _id:
          type: string
          example: 64c7c5f3e13a3a001f7e3d8f
        name:
          type: string
          example: Piter Pane
        email:
          type: string
          example: piter1987@example.com
        phone:
          type: string
          example: +380501234567
        contactType:
          type: string
          example: work
        isFavourite:
          type: boolean
          example: false
        photo:
          type: string
          example: https://res.cloudinary.com/demo/image/upload/sample.jpg
