openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact Book API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    This is an API documentation for the Contact Book backend application.

tags:
  - name: Auth
    description: User authentication
  - name: Contacts
    description: Managing contacts

servers:
  - url: https://nodejs-hw-mongodb-7-qxr1.onrender.com
  - url: http://localhost:3000

security:
  - bearerAuth: []

paths:
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'

  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{contactId}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{contactId}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{contactId}/delete.yaml'

  /auth/login:
    post:
      $ref: '../swagger/paths/contacts/auth/login.yaml'

  /auth/register:
    post:
      $ref: '../swagger/paths/contacts/auth/register.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
